indent

diff --git a/ssc b/ssc
--- a/ssc
+++ b/ssc
@@ -18,23 +18,23 @@ while [ -n "$1" ]; do
 done
 eval set -- $POSITIONAL_ARGS
 if [ -n "$SHOW_USAGE" -o  $# != 2 ]; then
-    echo "Usage: $0 [-4] [-u] [-s] [-r] [-e|-E file] [-0] <script> <binary>"
-    echo "  -4, --rc4                encrypt script with rc4 instead of compile time obfuscation"
-    echo "                           additionally, remove script size limit"
-    echo "  -u, --untraceable        make untraceable binary"
-    echo "                           enable debugger detection, abort program when debugger is found"
-    echo "  -s, --static             make static binary"
-    echo "                           link statically, binary is more portable but bigger"
-    echo "  -r, --random-key         use random key for obfuscation and encryption"
-    echo "  -e, --embed-interpreter  embed specified interpreter into binary"
-    echo "                           the interpreter will be used no matter what shebang is"
-    echo "  -E, --embed-archive      embed specified tar.gz archive into binary, require libarchive-dev"
-    echo "                           set relative path in shebang to use an interpreter in the archive"
-    echo "  -0, --fix-argv0          try to fix \$0, may not work"
-    echo "                           if it doesn't work or causes problems, use \$SSC_ARGV0 instead"
-    echo "  -v, --verbose            show debug messages"
-    echo "  -h, --help               display this help and exit"
-    exit 0
+  echo "Usage: $0 [-4] [-u] [-s] [-r] [-e|-E file] [-0] <script> <binary>"
+  echo "  -4, --rc4                encrypt script with rc4 instead of compile time obfuscation"
+  echo "                           additionally, remove script size limit"
+  echo "  -u, --untraceable        make untraceable binary"
+  echo "                           enable debugger detection, abort program when debugger is found"
+  echo "  -s, --static             make static binary"
+  echo "                           link statically, binary is more portable but bigger"
+  echo "  -r, --random-key         use random key for obfuscation and encryption"
+  echo "  -e, --embed-interpreter  embed specified interpreter into binary"
+  echo "                           the interpreter will be used no matter what shebang is"
+  echo "  -E, --embed-archive      embed specified tar.gz archive into binary, require libarchive-dev"
+  echo "                           set relative path in shebang to use an interpreter in the archive"
+  echo "  -0, --fix-argv0          try to fix \$0, may not work"
+  echo "                           if it doesn't work or causes problems, use \$SSC_ARGV0 instead"
+  echo "  -v, --verbose            show debug messages"
+  echo "  -h, --help               display this help and exit"
+  exit 0
 fi
 
 DIR="$(dirname "$0")/src"
@@ -44,11 +44,11 @@ DIR="$(dirname "$0")/src"
 
 CXX_STANDARD=c++14
 case "$(uname -s)" in
-    Linux*)       MACHINE=Linux;;
-    Darwin*)      MACHINE=Mac;;
-    CYGWIN*)      MACHINE=Cygwin; CXX_STANDARD=gnu++14;;
-    MINGW*|MSYS*) echo "please use cygwin"; exit 1;;
-    *)            echo "unsupported system"; exit 1;;
+  Linux*)       MACHINE=Linux;;
+  Darwin*)      MACHINE=Mac;;
+  CYGWIN*)      MACHINE=Cygwin; CXX_STANDARD=gnu++14;;
+  MINGW*|MSYS*) echo "please use cygwin"; exit 1;;
+  *)            echo "unsupported system"; exit 1;;
 esac
 
 [ -x "$(command -v termux-info)" ] && LDFLAGS="$LDFLAGS -landroid-wordexp"
